.PHONY: run build test cover vet tidy{{if .Auth}} token{{end}}{{if .Opt.HasExtra "docker-compose"}} up down{{end}}

run:
	go run ./cmd/server

build:
	go build -o bin/{{.Opt.Name}} ./cmd/server

test:
	go test ./...

cover:
	go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out

vet:
	gofmt -l . && go vet ./...

tidy:
	go mod tidy
{{- if .Auth}}

# A development token signed with JWT_SECRET: make token SUB=alice
token:
	@go run ./cmd/token -sub $(or $(SUB),dev-user)
{{- end}}
{{- if .Opt.HasExtra "docker-compose"}}

up:
	docker compose up --build

down:
	docker compose down
{{- end}}
