// Package entity adds a CRUD resource (domain type, service, repository,
// HTTP handlers, migration and tests) to a project generated by projgen.
package entity

import (
	"errors"
	"fmt"
	"regexp"
	"slices"
	"strings"
)

// Field is one column of an entity.
type Field struct {
	Name     string // snake_case, as typed: "category_id"
	Type     string // string | text | int | int64 | float | bool | time
	Required bool   // strings must be non-empty
}

// Spec is a parsed "projgen add entity" request.
type Spec struct {
	Name   string // as typed: "Product", "order_item"
	Fields []Field
}

var types = map[string]bool{"string": true, "text": true, "int": true, "int64": true, "float": true, "bool": true, "time": true}

// TypeNames lists the supported field types for help text.
const TypeNames = "string, text, int, int64, float, bool, time"

var (
	entityRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]{0,40}$`)
	fieldRe  = regexp.MustCompile(`^[a-z][a-z0-9_]{0,40}$`)
)

// SQL keywords that would need quoting as table or column names.
var reserved = []string{"all", "and", "as", "by", "case", "check", "column", "default", "desc", "asc", "distinct",
	"from", "group", "having", "in", "index", "key", "limit", "not", "null", "offset", "on", "or", "order",
	"primary", "references", "select", "table", "to", "union", "unique", "user", "where", "with",
	"groups", "keys", "rows"} // reserved table names in MySQL 8

// Parse reads "Product" and "name:string:required" style arguments.
func Parse(name string, args []string) (Spec, error) {
	var errs []error
	if !entityRe.MatchString(name) {
		errs = append(errs, fmt.Errorf("entity name %q: use letters, digits and _ starting with a letter, e.g. Product or order_item", name))
	} else if slices.Contains(reserved, plural(snake(name))) {
		errs = append(errs, fmt.Errorf("entity name %q is an SQL keyword; choose another", name))
	}
	if len(args) == 0 {
		errs = append(errs, errors.New("give at least one field, e.g. name:string:required"))
	}
	s := Spec{Name: name}
	seen := map[string]bool{}
	for _, a := range args {
		parts := strings.Split(a, ":")
		if len(parts) < 2 || len(parts) > 3 {
			errs = append(errs, fmt.Errorf("field %q: use name:type or name:type:required", a))
			continue
		}
		f := Field{Name: parts[0], Type: parts[1]}
		if len(parts) == 3 {
			if parts[2] != "required" {
				errs = append(errs, fmt.Errorf("field %q: the only modifier is \"required\"", a))
				continue
			}
			f.Required = true
		}
		switch {
		case !fieldRe.MatchString(f.Name):
			errs = append(errs, fmt.Errorf("field %q: use snake_case, e.g. unit_price", f.Name))
		case f.Name == "id" || f.Name == "created_at" || f.Name == "updated_at":
			errs = append(errs, fmt.Errorf("field %q is added automatically", f.Name))
		case slices.Contains(reserved, f.Name):
			errs = append(errs, fmt.Errorf("field %q is an SQL keyword; choose another", f.Name))
		case !types[f.Type]:
			errs = append(errs, fmt.Errorf("field %q: type %q not supported; use one of: %s", f.Name, f.Type, TypeNames))
		case f.Required && f.Type != "string" && f.Type != "text":
			errs = append(errs, fmt.Errorf("field %q: required applies to string and text fields only", f.Name))
		case seen[f.Name]:
			errs = append(errs, fmt.Errorf("field %q listed twice", f.Name))
		}
		seen[f.Name] = true
		s.Fields = append(s.Fields, f)
	}
	return s, errors.Join(errs...)
}

// words splits "OrderItem", "order_item" or "orderItem" into lower-case words.
func words(s string) []string {
	var out []string
	var cur []rune
	rs := []rune(s)
	for i, r := range rs {
		switch {
		case r == '_':
			if len(cur) > 0 {
				out = append(out, string(cur))
				cur = nil
			}
			continue
		case r >= 'A' && r <= 'Z':
			// Start a new word at "aB" or at "ABc" (the B in "HTTPServer").
			if len(cur) > 0 && (isLower(rs[i-1]) || (i+1 < len(rs) && isLower(rs[i+1]) && isUpper(rs[i-1]))) {
				out = append(out, string(cur))
				cur = nil
			}
			r += 'a' - 'A'
		}
		cur = append(cur, r)
	}
	if len(cur) > 0 {
		out = append(out, string(cur))
	}
	return out
}

func isLower(r rune) bool { return r >= 'a' && r <= 'z' || r >= '0' && r <= '9' }
func isUpper(r rune) bool { return r >= 'A' && r <= 'Z' }

var initialisms = map[string]string{"id": "ID", "url": "URL", "api": "API", "http": "HTTP", "json": "JSON", "uuid": "UUID", "sku": "SKU", "ip": "IP", "sql": "SQL"}

func pascal(s string) string {
	var b strings.Builder
	for _, w := range words(s) {
		if up, ok := initialisms[w]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(w[:1]) + w[1:])
	}
	return b.String()
}

func camel(s string) string {
	ws := words(s)
	if len(ws) == 0 {
		return ""
	}
	return ws[0] + pascal(strings.Join(ws[1:], "_"))
}

func snake(s string) string { return strings.Join(words(s), "_") }

// plural pluralises the last word of a snake_case name.
func plural(s string) string {
	switch {
	case strings.HasSuffix(s, "y") && len(s) > 1 && !strings.ContainsAny(s[len(s)-2:len(s)-1], "aeiou"):
		return s[:len(s)-1] + "ies"
	case strings.HasSuffix(s, "s"), strings.HasSuffix(s, "x"), strings.HasSuffix(s, "z"),
		strings.HasSuffix(s, "ch"), strings.HasSuffix(s, "sh"):
		return s + "es"
	}
	return s + "s"
}
